version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alinaursova/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    image: alinaursova/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: alinaursova/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media/
    ports:
      - 8000:80