# Generated by Django 3.2.3 on 2023-10-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231003_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_subcribed',
            new_name='is_subscribed',
        ),
    ]
